name = "yield"
main = "worker.js"
account_id = "a928f4bf274d697272e1ddf90cb49798"
workers_dev = true
compatibility_date = "2026-03-20"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[observability]
enabled = true

[vars]
CORS_ALLOWED_ORIGINS = "http://localhost:3001,https://yield-53r.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "yield-db"
database_id = "5fa60998-77f6-4087-b54f-a7e54734fd5a"
preview_database_id = "5fa60998-77f6-4087-b54f-a7e54734fd5a"